changes for singularity + slurm

diff --git a/advanced/hpc_compute_to_data/wrap_singularity b/advanced/hpc_compute_to_data/wrap_singularity
--- a/advanced/hpc_compute_to_data/wrap_singularity
+++ b/advanced/hpc_compute_to_data/wrap_singularity
@@ -1,64 +1,88 @@
 #!/bin/bash
 DIR=$(dirname "$0")
-REL_PATH_TO_COMPUTE="../compute/"
+PATH_TO_COMPUTE=~irods/compute
 singularity="/usr/local/bin/singularity"
 SINGULARITY_DATA_ROOT="/tmp/irods" #needs 'src' and 'dst' subdirectories
 
-. "${DIR}/${REL_PATH_TO_COMPUTE}"/singularity_images.conf
+. "${PATH_TO_COMPUTE}"/singularity_images.conf
 
 subcommand="$1"; shift
 
-[ -z "$subcommand" ] && 
-{
+[ -z "$subcommand" ] && {
   echo $'\n\t'"== Local singularity images index =="$'\n'
   for key in ${!Singularity_Sources[*]}; do
     echo "$key"$'\t\t'"${Singularity_Sources[$key]}"
   done
   echo $'\n'
-  exit  0
-
+  exit 0
 } >&2
 
-# -- Helper function to pull singularity images
+if [ $subcommand = "nop" ] ; then
+  exit 0
+fi
 
 pull_image() {  
-  [ -n "$1" ] && [[ $1 != */* ]] || return 2; 
-  LOC=$(readlink -e "${DIR}/${REL_PATH_TO_COMPUTE}")/"$1.simg"
-  echo -n "$LOC - being pulled ... " >&2
-  if [ ! -f "$LOC" ]  ; then
-      SOURCE="${Singularity_Sources[$1]}" 
-      echo  "using '$SOURCE'" >&2
-      [ -n "$SOURCE" ] || return 1
-      echo -n "  (please wait ...)"
-      ( cd $DIR && ${singularity} pull --name $(basename "$LOC") "$SOURCE"  && \
-        mv $(basename "$LOC") "$REL_PATH_TO_COMPUTE"/.
-      ) >/dev/null 2>&1
-      echo 
-  else
-      echo  " already exists" >&2
-  fi
+   [ -n "$1" ] && [[ $1 != */* ]] || return 2; 
+   local TGT="${PATH_TO_COMPUTE}/$1.simg"
+   echo "$TGT - being pulled. " >&2
+   if [ ! -f "$TGT" ]  ; then
+       SOURCE="${Singularity_Sources[$1]}" 
+       [ -n "$SOURCE" ] || { echo -n "image URI not found, try:" 
+         echo " shub://... or docker://... " >&2 ; return 1 ; }
+       echo  $'\t using '"'$SOURCE'" >&2
+       echo  $'\t (please wait ...)' >&2
+       ( cd $DIR && ${singularity} pull --name $(basename "$TGT") "$SOURCE"  && \
+         mv $(basename "$TGT") "$PATH_TO_COMPUTE"/.
+       ) >/dev/null 2>&1
+       echo  >&2 # carriage return
+   else
+       echo  $'\t already exists' >&2
+   fi
 }
 
 case "$1" in 
-metadata_addtags)
-  case "$subcommand" in 
-    pull) pull_image $1 ;;
-  esac
-;;
-thumbnail_image)
-  case $subcommand in
-    exec) 
-	cd "${DIR}${REL_PATH_TO_COMPUTE}"
-        if [ "$2 $3" != 'python3 /make_thumbnail.py' ]; then exit 1; else 
-          IMAGE="$1" ; shift 3
-	  ${singularity} exec -c \
-	    --bind ${SINGULARITY_DATA_ROOT}/src:/src \
-            --bind ${SINGULARITY_DATA_ROOT}/dst:/dst \
-	    "$IMAGE".simg python3 /make_thumbnail.py "$1" "/src/$2" "/dst/$3" "$4"
-        fi
-    ;;
-    pull) pull_image $1 ;;
-  esac
-;;
-*)exit 123;;
+
+  metadata_addtags)
+
+    case "$subcommand" in 
+
+      pull) pull_image $1 ;;
+
+      exec) IMAGE="$1" ; shift 
+
+	cd "${PATH_TO_COMPUTE}"
+        ${singularity} run "$IMAGE".simg "$@"
+
+    esac
+  ;;
+
+  thumbnail_image)
+
+    case $subcommand in
+
+      pull) pull_image $1 ;;
+
+      exec) IMAGE="$1" ; shift
+
+        dir_bind_opts=""; shopt -s extglob
+        while [[ $1 = --bind && $2 = /*:/@(dst|src) ]]; do
+          dir_bind_opts+=" $1 $2 "; shift 2
+        done
+	cd "${PATH_TO_COMPUTE}" 
+        #-- docker-inherited container; use specific python binary and scriptname
+	if [[ $1 = /usr/*/python3 && $2 = /make_thumbnail.py ]]; then
+	  shift 2
+	  ${singularity} exec -c $dir_bind_opts "$IMAGE".simg \
+            '/usr/local/bin/python3' '/make_thumbnail.py' "$1" "/src/$2" "/dst/$3" "$4"
+        else
+          exit 1
+	fi
+      ;;
+
+    esac
+  ;;
+
+  #-- invalid image name
+  *) exit 2 ;;
+
 esac
